
#-----------------------------------------------------------------------------------------------------
#                               University of Torino - Department of Physics
#                                   via Giuria 1 10125, Torino, Italy
#-----------------------------------------------------------------------------------------------------
# [Filename]       Makefile
# [Project]        Advanced Electronics Laboratory course
# [Author]         Luca Pacher - pacher@to.infn.it
# [Language]       GNU Makefile
# [Created]        Mar 05, 2016
# [Modified]       Mar 05, 2016
# [Description]    Simple Makefile to run a complete non-project mode FPGA implementation flow using
#                  Xilinx Vivado
# [Notes]          Edit $(TCL_DIR)/flow.tcl and $(TCL_DIR)/download.tcl Tcl scripts in order to fit 
#                  your current HDL design 
# [Version]        1.0
# [Revisions]      05.03.2015 - Created
#-----------------------------------------------------------------------------------------------------



## Tcl scripts directory
TCL_DIR = ${PWD}/scripts


## log files directory
LOG_DIR = ${PWD}/log


## outputs directory (bitstream, checkpoint snapshots)
OUT_DIR = ${PWD}/results


## some useful aliases
RM = rm -f
RMDIR = rm -rf


## include targets implementation file
include ./Makefile.defs
